version: '3.8'

services:
  monitorng-ont:
    image: medot26/monitoring-ont:latest
    container_name: monitorng-ont-app
    restart: unless-stopped
    ports:
      - "3070:3000"
    environment:
      - GENIEACS_URL=http://192.168.0.0:7557
      - GENIEACS_AUTH=admin:xxxxxx
      - WA_API_KEY=e4xxxxxxxx
      - WA_TARGET_NUMBERS=43242355xxxxx@g.us
      - POLL_INTERVAL_MINUTES=1
      - RX_WARNING_THRESHOLD="-27"
      - TZ=Asia/Jakarta
    # Optional: Map a logs directory if you eventually write logs to a file
    # volumes:
    #   - ./logs:/usr/src/app/logs
